# -*- coding: utf-8 -*-
"""week3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dYe9L86AUUFckb8BeC0bftL9yK9VDE0U

from google colab import files #匯入套件

import pandas as pd

upload = files.upload() #開啟上傳介面並載入

data = pd.read_csv("剛剛上傳的檔案名稱")
"""

from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

import os
os.chdir("/content/gdrive/My Drive/")
!ls -l "/content/gdrive/My Drive/"

#!ls -l "自行填寫正確的路徑"

import pandas as pd

csv_file = './112-2 LATIA/week2/112_student.csv'
#csv_file ="自行填寫正確的路徑"

#columns = [
#    "學年度","學校代碼","學校名稱","日間∕進修別","等級別","總計","男生計",
#    "女生計","一年級男","一年級女","二年級男","二年級女","三年級男","三年級女",
#    "四年級男","四年級女","五年級男","五年級女","六年級男","六年級女",
#    "七年級男","七年級女","延修生男","延修生女","縣市名稱","體系別"
#]
df = pd.read_csv(csv_file)
#print(df.head())

#查看資料欄位資訊
print(df.info())

#查看資料的統計學資訊描述
print(df.describe())

import pandas as pd

csv_file = './112-2 LATIA/week2/112_student.csv'


df = pd.read_csv(csv_file, encoding='utf-8')
#print(df.head())

#查看資料欄位資訊
#print(df.info())
print(df.describe(include='all'))

# 對Embarked登船港口作計數畫橫條圖
data.Embarked.value_counts().plot.barh(x='Port of Embarkation', y='number of people')

"""1. 台大和政治大學的人數總和
2. 男生計小於1000
3. 哪間大學的博士總人數最多
"""

n_rows=len(df)
print(n_rows)
total=0
for n in range(n_rows):
    if(df.iloc[n,2]=='國立政治大學') or (df.iloc[n,2]=='國立臺灣大學'):
        total+=df.iloc[n,5]
    else:
        continue
print('total =' + str(total))
#print(df[['學校名稱','男生計','女生計']])

for n in range(n_rows):
    if(df.iloc[n,6]<=1000):
        print(f'{df.iloc[n,2]} = {df.iloc[n,6]}')
    else:
        continue

D_max=0
D_max_name=''
for n in range(n_rows):
    if(df.iloc[n,4]=='D 博士') and (df.iloc[n,5]>D_max):
        D_max=df.iloc[n,5]
        D_max_name=df.iloc[n,2]
    else:
        continue
print(str(D_max_name) + '=>' + str(D_max))





# 對Embarked登船港口畫圓餅圖
data.Embarked.value_counts().plot(kind='pie')

# 對Pclass購票等級作計數
data.Pclass.value_counts()

# 對Pclass購票等級畫橫條圖
data.Pclass.value_counts().plot.barh(x='Pclasses', y='number of people')

# 對Pclass購票等級畫圓餅圖
data.Pclass.value_counts().plot(kind='pie')

# 對Pclass購票等級畫箱型圖
data.Pclass.value_counts().plot(kind='box')

# 只取Pclass為1的紀錄
class_1 = data.Pclass[data.Pclass == 1]
print('只取Pclass為1的紀錄\n', class_1.head())

# 只取Pclass為2的紀錄
class_2 = data.Pclass[data.Pclass == 2]
print('只取Pclass為2的紀錄\n', class_2.head())

# 只取Pclass為3的紀錄
class_3 = data.Pclass[data.Pclass == 3]
print('只取Pclass為3的紀錄\n', class_3.head())

# 只取Pclass大於1的紀錄
below_1 = data.Pclass[data.Pclass > 1]
print('只取Pclass大於1的紀錄\n', below_1.head())

# 只取Pclass大於2的紀錄
below_2 = data.Pclass[data.Pclass > 2]
print('只取Pclass大於2的紀錄\n', below_2.head())

# 對Fare票價畫長條圖
data.Fare.hist()

# 將資料以Age以及Pclass分群後取Fare之算術平均數的折線圖
data.groupby(['Age', 'Pclass']).mean()['Fare'].plot()

# 顯示所有表徵之間的關聯性
from pandas.plotting import scatter_matrix
scatter_matrix(data, alpha=0.5, diagonal='kde')
plt.show()

# 將票價資料從英鎊轉換為台幣計價
fare_in_twd = data.Fare * 40.8
# 將票價資料從英鎊轉換為美金計價
fare_in_twd = data.Fare * 1.31